name: Deploy Website

on:
  push:
    branches: [ "main" ]   # Tự động chạy khi push code lên main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload website files
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./   # nếu code web ở thư mục gốc; nếu code build ra /dist thì sửa thành dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
